name: Continuous integration

on: [push]

jobs:

  apk:
    name: Build APK
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Build debug APK
        run: ./gradlew assembleDebug
